# Generated by Django 5.2.13 on 2026-04-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_project_creators_to_memberships(apps, schema_editor):
    Project = apps.get_model("calendarfunc", "Project")
    ProjectMembership = apps.get_model("calendarfunc", "ProjectMembership")
    memberships = [
        ProjectMembership(project_id=project.id, user_id=project.creator_id)
        for project in Project.objects.exclude(creator_id=None)
    ]
    ProjectMembership.objects.bulk_create(memberships, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('calendarfunc', '0003_project_login_project_password_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата входа в проект')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='calendarfunc.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'участник проекта',
                'verbose_name_plural': 'участники проектов',
                'ordering': ['-joined_at'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.RunPython(add_project_creators_to_memberships, migrations.RunPython.noop),
    ]
