# Generated by Django 5.2.13 on 2026-04-28 15:30

from django.db import migrations, models


def set_project_creator_admin_role(apps, schema_editor):
    Project = apps.get_model("calendarfunc", "Project")
    ProjectMembership = apps.get_model("calendarfunc", "ProjectMembership")
    for project in Project.objects.all():
        ProjectMembership.objects.filter(project_id=project.id, user_id=project.creator_id).update(role=1.0)


class Migration(migrations.Migration):

    dependencies = [
        ('calendarfunc', '0004_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='role',
            field=models.FloatField(default=10.0, verbose_name='Роль в проекте'),
        ),
        migrations.RunPython(set_project_creator_admin_role, migrations.RunPython.noop),
    ]
