# Generated by Django 5.2.13 on 2026-04-28 15:30

from django.db import migrations, models


def copy_numeric_role_to_app_role(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.filter(is_superuser=True).update(app_role="superadmin")
    User.objects.filter(role=0.0).update(app_role="superadmin")
    User.objects.filter(role=1.0).exclude(app_role="superadmin").update(app_role="admin")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Админ'), ('user', 'Пользователь'), ('guest', 'Гость')], default='user', max_length=20, verbose_name='Роль в приложении'),
        ),
        migrations.RunPython(copy_numeric_role_to_app_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.FloatField(default=10.0, verbose_name='Устаревшая числовая роль'),
        ),
    ]
